### ISSUE TITLE
FAQ Category locked, Questions? Ask Here!  Category created (name it whatever lol)

### ISSUE THREAD

**Issue by ger630** [sweepsatlas/issues#44]

**Comment by sixty4bit** [comment]
I have locked down the FAQ category. We have a "Questions" category in the "Suggestions, Bug Reports & Feedback" category. Why doesn't that work?

**Comment by sixty4bit** [comment]
I believe this is now fixed. Please verify and close if it is. If something else needs to be done please let me know.

**Comment by ger630** [comment]
I do not see a new category and I do not see the FAQ category locked.

**Comment by sixty4bit** [comment]
FAQ is set to allow only you and I to create new posts. People can see and reply. If we don't want them to reply to things then we can close them. 

Why doesn't "Suggestions, Bug Reports & Feedback" category fit the need for "Questions"?
