### ISSUE TITLE
Moderate function

### ISSUE THREAD

**Issue by ger630** [sweepsatlas/issues#86]
Create a button that when active will unfilter any filters in the prefrenses panel activated.
Really for moderators to see all the sweeps without looking at hidden.

**Comment by sixty4bit** [comment]
What is the goal here? I understand you want to override all of the preferences you have set, but why? What are you actually looking for when you are doing this?

**Comment by ger630** [comment]
If acting as a moderator you need to find or look at multiple sweeps at once the fact that you have items hidden can create an issue especially if looking for a duplicate and one might have a tag that hides it while the duplicate does not.  I have no specific issue in mind but see a need to be able to see all sweeps without filtering on certain occasions in the course of moderating the sweeps.

You will never have this problem but a moderator might..

**Comment by sixty4bit** [comment]
I think the moderators need a completely separate interface. I don't think it wise to build it into the same interface as the one that is used by the users. I just don't know what that interface looks like :-( Or what it needs to do. I totally understand the "show me everything" use case. But what are the other contexts there? 

At the same time, I don't really want to rebuild the UI we already have :-)

**Comment by sixty4bit** [comment]
closed by sweepsatlas/sweeps#169
