### ISSUE TITLE
Site Search to search URLs of the sweeps.

### ISSUE THREAD

**Issue by ger630** [sweepsatlas/issues#94]
That way yo can easily see if a sweep has been listed in the database or find a sweep by the url.

**Comment by sixty4bit** [comment]
This should work as expected. Copy a link to a sweepstakes, paste it into search, and hit enter.

You should get that one entry back.

You can then delete everything but the domain, and you should get all sweeps related to that domain. Apparently I implemented this 5 months ago :D
